"""Generating tools from a description, and verifying what they can do.

A generated tool is written **disabled**. Creation, review and enabling are
three separate acts, because a tool is invoked by a *model*, on its own
initiative, mid-conversation — consent given once at creation is not consent
for every later autonomous call. `domains/creation.py` writes a domain that is
live on next load, and that is correct there: a domain runs when the user types
its command.

The manifest declares which capabilities the tool needs. That declaration is
generated by the model but **verified against the source by static analysis**,
because a model's own account of what its code does is not evidence.
"""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path

import yaml

from tawn.capability.grants import CAPABILITIES

TOOLS_REL = "tools"
MANIFEST = "tool.yaml"
IMPL = "impl.py"
TEST = "test_impl.py"


class CapabilityMismatch(Exception):
    """The manifest claims fewer capabilities than the code actually uses."""


class ToolGenerationError(Exception):
    """The model did not produce a usable tool."""


#: import → capability it implies.
_MODULE_CAPS: dict[str, str] = {
    "subprocess": "shell", "os": "shell", "pty": "shell", "commands": "shell",
    "socket": "net", "httpx": "net", "requests": "net", "urllib": "net",
    "http": "net", "aiohttp": "net", "ftplib": "net", "smtplib": "net",
    "telnetlib": "net", "websockets": "net", "paramiko": "net",
    "shutil": "write", "tempfile": "write", "pathlib": "read",
}

#: bare call name → capability it implies.
_CALL_CAPS: dict[str, str] = {
    "system": "shell", "popen": "shell", "spawn": "shell", "execv": "shell",
    "run": "shell", "check_output": "shell", "call": "shell",
    "urlopen": "net", "get": "net", "post": "net", "request": "net",
    "remove": "write", "unlink": "write", "rmdir": "write", "mkdir": "write",
    "rename": "write", "replace": "write", "write_text": "write",
    "write_bytes": "write", "read_text": "read", "read_bytes": "read",
    "eval": "shell", "exec": "shell", "compile": "shell",
    "__import__": "shell",
}

_WRITE_MODES = ("w", "a", "x", "+")


def inspect_source(source: str) -> set[str]:
    """Capabilities the code actually uses, by walking its AST.

    Deliberately over-reports rather than under: `pathlib` counts as `read`
    even when only used to join paths. A false positive costs the user one
    extra grant; a false negative is a capability with no gate.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        raise ToolGenerationError(f"generated code does not parse: {exc}") from exc

    caps: set[str] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]
                if root in _MODULE_CAPS:
                    caps.add(_MODULE_CAPS[root])
        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".")[0]
            if root in _MODULE_CAPS:
                caps.add(_MODULE_CAPS[root])
        elif isinstance(node, ast.Call):
            name = _call_name(node.func)
            if name in _CALL_CAPS:
                caps.add(_CALL_CAPS[name])
            if name == "open":
                caps.add(_open_capability(node))

    caps.discard("")
    return caps


def _call_name(func: ast.expr) -> str:
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return ""


def _open_capability(node: ast.Call) -> str:
    """`open(p)` reads; `open(p, 'w')` writes."""
    mode = ""
    if len(node.args) > 1 and isinstance(node.args[1], ast.Constant):
        mode = str(node.args[1].value)
    for kw in node.keywords:
        if kw.arg == "mode" and isinstance(kw.value, ast.Constant):
            mode = str(kw.value.value)
    return "write" if any(m in mode for m in _WRITE_MODES) else "read"


_PROMPT = """Write a Python tool for a personal AI assistant.

What it should do: {description}

Reply in exactly this format. Use these headings literally, in this order.

NAME: snake_case_name
DESCRIPTION: one sentence, written for a model deciding whether to call it
CAPABILITIES: comma-separated, from {caps} — or the word none
PARAMETERS:
```json
{{"type": "object", "properties": {{"arg": {{"type": "string", "description": "..."}}}}, "required": ["arg"]}}
```
IMPL:
```python
def run(arg: str) -> str:
    return "result"
```
TEST:
```python
def test_run():
    assert run("x")
```

Rules for the implementation:
- Define exactly one function named `run`, taking the parameters above as
  keyword arguments and returning a string.
- Use only the standard library plus httpx.
- Handle its own errors and return a readable message instead of raising.
- No work at import time.

Rules for capabilities: list every one the code needs. `read` for reading
files, `write` for writing them, `net` for network access, `shell` for running
commands. Declaring more than you need is safe; declaring fewer is detected by
static analysis and the tool is rejected."""

_RETRY_NOTE = (
    "\n\nYour previous reply could not be parsed ({error}). Reply again using "
    "exactly the headings NAME:, DESCRIPTION:, CAPABILITIES:, PARAMETERS:, "
    "IMPL:, TEST: — and nothing else."
)


def _strip_fence(block: str) -> str:
    block = block.strip()
    m = re.match(r"^```[a-zA-Z]*\s*\n(.*?)\n?```\s*$", block, re.S)
    return (m.group(1) if m else block).strip()


_SECTIONS = ("NAME", "DESCRIPTION", "CAPABILITIES", "PARAMETERS", "IMPL", "TEST")


def parse_sections(text: str) -> dict:
    """Read the delimited reply format.

    Preferred over JSON because a tool's payload *contains Python source*, and
    embedding that in a JSON string requires the model to escape every newline
    and quote correctly — the single most common way a smaller model's output
    becomes unparseable. Fenced blocks need no escaping at all.
    """
    if not text:
        return {}
    # Split on the headings, keeping what follows each.
    pattern = r"^\s*(" + "|".join(_SECTIONS) + r")\s*:[ \t]*"
    parts = re.split(pattern, text, flags=re.M)
    if len(parts) < 3:
        return {}
    out: dict = {}
    for i in range(1, len(parts) - 1, 2):
        out[parts[i].strip().upper()] = parts[i + 1].strip()
    if "NAME" not in out or "IMPL" not in out:
        return {}

    caps_raw = _strip_fence(out.get("CAPABILITIES", ""))
    caps = [
        c.strip().lower()
        for c in re.split(r"[,\s]+", caps_raw)
        if c.strip() and c.strip().lower() not in ("none", "-", "[]")
    ]

    params: dict = {"type": "object", "properties": {}}
    raw_params = _strip_fence(out.get("PARAMETERS", ""))
    if raw_params:
        try:
            parsed = json.loads(repair_json(raw_params))
            if isinstance(parsed, dict):
                params = parsed
        except Exception:
            # A malformed schema is recoverable — the tool still runs, the
            # model just gets a looser signature. A malformed *body* is not.
            pass

    return {
        "name": _strip_fence(out["NAME"]).strip().strip("`\"'"),
        "description": _strip_fence(out.get("DESCRIPTION", "")),
        "capabilities": caps,
        "parameters": params,
        "impl": _strip_fence(out["IMPL"]),
        "test": _strip_fence(out.get("TEST", "")),
    }


def repair_json(raw: str) -> str:
    """Make common near-JSON parseable: models emit JS and Python literals.

    Only structural repairs, never semantic ones — this fixes how the payload
    was quoted, not what it says.
    """
    text = raw.strip()
    # // and # line comments
    text = re.sub(r"^\s*(//|#).*$", "", text, flags=re.M)
    # Python singletons
    text = re.sub(r"\bTrue\b", "true", text)
    text = re.sub(r"\bFalse\b", "false", text)
    text = re.sub(r"\bNone\b", "null", text)
    # unquoted keys → quoted
    text = re.sub(r"([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*:)", r'\1"\2"\3', text)
    # single-quoted keys and simple values → double-quoted
    text = re.sub(r"'([^'\\]*)'(\s*:)", r'"\1"\2', text)
    text = re.sub(r"(:\s*)'([^'\\]*)'", r'\1"\2"', text)
    # trailing commas
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    return text


def _balanced_object(text: str) -> str | None:
    """The first complete `{...}` in a string, brace-matched and string-aware.

    A greedy regex grabs from the first brace to the *last* one anywhere in
    the reply, which silently swallows trailing prose into the payload.
    """
    start = text.find("{")
    if start == -1:
        return None
    depth, in_str, esc = 0, False, False
    for i in range(start, len(text)):
        ch = text[i]
        if esc:
            esc = False
            continue
        if ch == "\\":
            esc = True
            continue
        if ch == '"':
            in_str = not in_str
            continue
        if in_str:
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return None


def _extract_json(text: str) -> dict:
    """Last-resort JSON path, for models that ignore the section format."""
    raw = (text or "").strip()
    fenced = re.match(r"^```(?:json)?\s*\n(.*?)\n?```\s*$", raw, re.S)
    if fenced:
        raw = fenced.group(1).strip()
    # Brace-match unconditionally, not only when the reply *starts* with prose:
    # a payload followed by "Hope that helps!" is just as common, and taking
    # the whole string then fails with "Extra data".
    found = _balanced_object(raw)
    if not found:
        raise ToolGenerationError("no JSON object and no NAME:/IMPL: sections")
    raw = found
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Models routinely emit JS/Python object literals. Repair the quoting
        # rather than failing on it.
        try:
            return json.loads(repair_json(raw))
        except json.JSONDecodeError as exc:
            raise ToolGenerationError(f"unparseable JSON: {exc}") from exc


def parse_reply(text: str) -> dict:
    """Read a model's reply in whichever form it arrived.

    Sections first (what the prompt asks for and what weaker models manage),
    then JSON, then repaired JSON. Accepting several shapes costs a few lines
    here and saves the user a failed generation they cannot act on.
    """
    sections = parse_sections(text)
    if sections:
        return sections
    data = _extract_json(text)
    return {
        "name": str(data.get("name") or "").strip(),
        "description": str(data.get("description") or ""),
        "capabilities": list(data.get("capabilities") or []),
        "parameters": data.get("parameters") or {"type": "object", "properties": {}},
        "impl": str(data.get("impl") or ""),
        "test": str(data.get("test") or ""),
    }


#: Fragments lifted straight from the prompt's example. A model too small for
#: the task echoes the template instead of writing code, and the result parses
#: perfectly while doing nothing — the worst failure mode, because it looks
#: like success.
_PLACEHOLDER_NAMES = {"snake_case_name", "snake_case", "snake", "your_tool", "tool_name"}
_PLACEHOLDER_BODIES = ('return "result"', "return 'result'")


def _looks_like_placeholder(name: str, impl: str) -> str | None:
    """Why this output is the template rather than a tool, or None."""
    if name.replace(" ", "_").lower() in _PLACEHOLDER_NAMES:
        return f"the model returned the placeholder name {name!r}"
    body = impl.strip()
    if any(ph in body for ph in _PLACEHOLDER_BODIES) and len(body.splitlines()) <= 3:
        return "the model returned the example body verbatim instead of writing code"
    return None


def _validate(data: dict, description: str) -> tuple[dict, str, str]:
    name = re.sub(r"[^a-z0-9_]+", "_", str(data.get("name") or "").strip().lower()).strip("_")
    impl = data.get("impl") or ""
    if not name:
        raise ToolGenerationError("the reply had no tool name")
    if not impl.strip():
        raise ToolGenerationError("the reply had no implementation")
    if "def run" not in impl:
        raise ToolGenerationError("the generated code defines no `run` function")
    # Parse now, so a syntax error is reported as a generation failure the
    # caller can retry rather than surfacing later as a mysterious import error.
    try:
        ast.parse(impl)
    except SyntaxError as exc:
        raise ToolGenerationError(f"generated code does not parse: {exc}") from exc

    echoed = _looks_like_placeholder(str(data.get("name") or ""), impl)
    if echoed:
        raise ToolGenerationError(echoed)

    manifest = {
        "name": name,
        "description": str(data.get("description") or description)[:400],
        "parameters": data.get("parameters") or {"type": "object", "properties": {}},
        "capabilities": [
            c for c in (data.get("capabilities") or []) if c in CAPABILITIES
        ],
        "enabled": False,
        "created_from": description[:400],
    }
    return manifest, impl, str(data.get("test") or "")


def generate_tool(
    description: str, router, allow_cloud: bool = False, retries: int = 1
) -> tuple[dict, str, str]:
    """Ask a model for a tool. Returns (manifest, impl, test).

    On an unparseable reply the model is told exactly what went wrong and asked
    again. A local model often gets the format right on the second attempt, and
    one retry is far cheaper than making the user rephrase.
    """
    from tawn.model.types import Message

    base = _PROMPT.format(description=description, caps=", ".join(CAPABILITIES))
    prompt = base
    first: Exception | None = None
    used_model = ""

    for _ in range(retries + 1):
        resp = router.complete(
            [Message(role="user", content=prompt)], sensitive=not allow_cloud
        )
        used_model = getattr(resp, "model", "") or used_model
        try:
            return _validate(parse_reply(resp.text), description)
        except ToolGenerationError as exc:
            # Report the *first* failure, not the last: a retry often drifts
            # further from the format, and the first error is the diagnostic
            # one.
            first = first or exc
            prompt = base + _RETRY_NOTE.format(error=exc)

    hint = ""
    if not allow_cloud:
        hint = (
            f" The local model{f' ({used_model})' if used_model else ''} may be too "
            "small to write code — writing a working tool needs a capable model. "
            "Try again with --cloud to use one of your configured cloud providers."
        )
    raise ToolGenerationError(f"{first}.{hint}")


def tool_dir(home: Path, name: str) -> Path:
    return Path(home) / TOOLS_REL / re.sub(r"[^a-z0-9_]+", "_", name.lower())


def write_tool(
    home: Path, name: str, manifest: dict, impl: str, test: str = ""
) -> Path:
    """Verify and write a tool. Always disabled.

    Raises `CapabilityMismatch` when the source needs more than the manifest
    admits — the check that makes the declaration mean something.
    """
    actual = inspect_source(impl)
    declared = set(manifest.get("capabilities") or [])
    missing = actual - declared
    if missing:
        raise CapabilityMismatch(
            f"the code uses {sorted(missing)} but the manifest declares "
            f"{sorted(declared) or 'nothing'}"
        )

    manifest = dict(manifest)
    manifest["name"] = name
    # Never trust an `enabled: true` arriving from a generator.
    manifest["enabled"] = False
    manifest.setdefault("capabilities", sorted(declared))

    d = tool_dir(home, name)
    d.mkdir(parents=True, exist_ok=True)
    (d / MANIFEST).write_text(yaml.safe_dump(manifest, sort_keys=False))
    (d / IMPL).write_text(impl)
    if test:
        (d / TEST).write_text(test)
    return d


def read_manifest(home: Path, name: str) -> dict | None:
    f = tool_dir(home, name) / MANIFEST
    if not f.is_file():
        return None
    try:
        return yaml.safe_load(f.read_text()) or None
    except Exception:
        return None


def read_source(home: Path, name: str) -> str | None:
    f = tool_dir(home, name) / IMPL
    return f.read_text(errors="replace") if f.is_file() else None


def set_enabled(home: Path, name: str, enabled: bool) -> bool:
    """Flip a tool's enabled flag. Only ever called for a human."""
    manifest = read_manifest(home, name)
    if manifest is None:
        return False
    manifest["enabled"] = bool(enabled)
    (tool_dir(home, name) / MANIFEST).write_text(
        yaml.safe_dump(manifest, sort_keys=False)
    )
    return True


def list_tools(home: Path) -> list[dict]:
    root = Path(home) / TOOLS_REL
    if not root.is_dir():
        return []
    out = []
    for d in sorted(root.iterdir()):
        if not d.is_dir():
            continue
        manifest = read_manifest(home, d.name)
        if manifest:
            out.append(manifest)
    return out


def remove_tool(home: Path, name: str) -> bool:
    import shutil

    d = tool_dir(home, name)
    if not d.is_dir():
        return False
    shutil.rmtree(d)
    return True
