"""Wiki generation with atomic swap.

On-disk layout — the only one that has ever existed:

    wiki/<domain>/index.md     per-domain knowledge index
    wiki/entities/<Name>.md    per-entity page, Obsidian-compatible
    wiki/links.json            graph data source
    wiki/conflicts.md          conflict log (written by conflicts.py)

Pages use `[[wikilinks]]` so the vault stays navigable in Obsidian, while
`links.json` gives the web graph a machine-readable source — the viewer never
parses markdown to find edges.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

_UNSAFE_NAME = re.compile(r"[^A-Za-z0-9 _.\-]")


# ── Domain indexes ────────────────────────────────────────────────────────────

def _template_index(domain: str, entities: list[str], recent_chunks: list[str]) -> str:
    entity_list = "\n".join(f"- {wikilink(e)}" for e in entities[:20]) or "_(none yet)_"
    recent_list = "\n".join(
        f"- {c[:120].replace(chr(10), ' ')}..." if len(c) > 120 else f"- {c}"
        for c in recent_chunks[:10]
    ) or "_(none yet)_"
    return (
        f"# {domain.title()} — Knowledge Index\n\n"
        f"## Key Entities\n\n{entity_list}\n\n"
        f"## Recent Notes\n\n{recent_list}\n\n"
        f"---\n_Auto-generated by Tawn Compiler. Edit `raw/` sources to update._\n"
    )


def generate_domain_index(
    domain: str,
    entities: list[str],
    recent_chunks: list[str],
    wiki_dir: Path,
    staging_dir: Path,
    router=None,
) -> None:
    """Write domain index.md to staging_dir/<domain>/index.md.

    Uses router for an LLM summary when available; falls back to template.
    """
    domain_staging = staging_dir / domain
    domain_staging.mkdir(parents=True, exist_ok=True)
    index_path = domain_staging / "index.md"

    if router is not None and recent_chunks:
        try:
            from tawn.model.types import Message
            prompt = (
                f"Write a concise wiki index for the '{domain}' domain. "
                f"Key entities: {', '.join(entities[:10])}. "
                f"Recent notes: {' | '.join(recent_chunks[:5])}. "
                f"Output markdown with a brief summary and entity list."
            )
            msgs = [Message(role="user", content=prompt)]
            text = ""
            for chunk in router.stream(msgs):
                text += chunk.text
                if chunk.done:
                    break
            if text.strip():
                index_path.write_text(text)
                return
        except Exception:
            pass

    index_path.write_text(_template_index(domain, entities, recent_chunks))


# ── Entity pages ──────────────────────────────────────────────────────────────

def wikilink(name: str) -> str:
    """Obsidian-compatible link. The vault and the web viewer read one file."""
    return f"[[{name}]]"


def _safe_filename(name: str) -> str:
    cleaned = _UNSAFE_NAME.sub("-", name).strip() or "unnamed"
    return f"{cleaned[:120]}.md"


def generate_entity_page(
    entity,
    related: list[tuple[str, str]],
    backlinks: list[str],
    staging_dir: Path,
) -> Path:
    """Write one entity page to staging_dir/entities/.

    `related` is [(name, relation)]; `backlinks` names the entities pointing
    *at* this one. Backlinks are listed as text rather than only drawn in the
    graph — they are what makes a wiki compound, and they need to stay
    readable and searchable, not only spatial.
    """
    out_dir = staging_dir / "entities"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / _safe_filename(entity.canonical)

    lines = ["---", f"entity: {entity.canonical}"]
    if entity.domain:
        lines.append(f"domain: {entity.domain}")
    if entity.confidence:
        lines.append(f"confidence: {entity.confidence}")
    lines += ["---", "", f"# {entity.canonical}", ""]

    if related:
        lines += ["## Related", ""]
        lines += [f"- {relation} → {wikilink(name)}" for name, relation in related]
        lines.append("")

    if backlinks:
        lines += ["## Linked from", ""]
        lines += [f"- {wikilink(name)}" for name in backlinks]
        lines.append("")

    lines += ["---", "_Auto-generated by Tawn. Edit `raw/` sources to update._"]
    path.write_text("\n".join(lines))
    return path


def generate_links_index(session, staging_dir: Path) -> Path:
    """Emit links.json — the graph's data source."""
    from tawn.memory.schema import Entity as _Entity, EntityEdge as _EntityEdge

    entities = session.query(_Entity).all()
    edges = session.query(_EntityEdge).all()
    ids = {e.id for e in entities}

    payload = {
        "nodes": [
            {"id": e.id, "label": e.canonical, "domain": e.domain,
             "confidence": e.confidence}
            for e in entities
        ],
        "links": [
            {"source": ed.from_entity_id, "target": ed.to_entity_id,
             "relation": ed.relation, "weight": ed.weight or 1}
            for ed in edges
            if ed.from_entity_id in ids and ed.to_entity_id in ids
        ],
    }
    staging_dir.mkdir(parents=True, exist_ok=True)
    path = staging_dir / "links.json"
    path.write_text(json.dumps(payload, indent=2))
    return path


# ── Atomic swap ───────────────────────────────────────────────────────────────

# Root-level directories that are not domains and must survive a swap.
_NON_DOMAIN_DIRS = {"entities"}


def atomic_swap(staging_dir: Path, wiki_dir: Path, prune: bool = True) -> None:
    """Move staged content into wiki_dir, one entry at a time.

    Each entry moves individually, so a failure leaves prior wiki content
    intact rather than a half-written tree.
    """
    if not staging_dir.exists():
        return

    # Captured before the move loop empties staging.
    staged_dirs = {
        d.name for d in staging_dir.iterdir()
        if d.is_dir() and not d.name.startswith(".")
    }

    for entry in list(staging_dir.iterdir()):
        if entry.name.startswith("."):
            continue

        if not entry.is_dir():
            # links.json and similar root-level artefacts
            dest_file = wiki_dir / entry.name
            if dest_file.exists():
                dest_file.unlink()
            shutil.move(str(entry), str(dest_file))
            continue

        dest = wiki_dir / entry.name
        tmp = wiki_dir / f".{entry.name}.tmp"
        if dest.exists():
            shutil.move(str(dest), str(tmp))
        shutil.move(str(entry), str(dest))
        if tmp.exists():
            shutil.rmtree(tmp)

    # Prune domains that no longer have a staged page — but only when the
    # caller staged something. An empty staging dir means the run generated
    # nothing (a compile where no file changed), not that every domain is
    # gone; pruning on that basis deleted all four domain indexes after an
    # uneventful compile.
    if not prune or not staged_dirs:
        return

    for live in list(wiki_dir.iterdir()):
        if (
            live.is_dir()
            and not live.name.startswith(".")
            and live.name not in staged_dirs
            and live.name not in _NON_DOMAIN_DIRS
        ):
            shutil.rmtree(live)
