"""Wiki generation with atomic swap.

Two public surfaces:

1. Domain-indexed generation (plan spec):
   generate_domain_index(domain, entities, recent_chunks, wiki_dir, staging_dir, router)
   atomic_swap(staging_dir, wiki_dir)

2. Full-corpus generation (used by legacy compiler path):
   generate_wiki(chunks, entities, wiki_dir)
"""

from __future__ import annotations

import shutil
from collections import defaultdict
from pathlib import Path

from tawn.compiler.parser import ParsedChunk
from tawn.memory.schema import Entity


def _domain_page(domain: str, chunks: list[ParsedChunk]) -> str:
    lines = [f"# Domain: {domain}\n"]
    for c in sorted(chunks, key=lambda x: x.source_path):
        lines.append(f"## `{c.source_path}` (chunk {c.chunk_index})")
        preview = c.content[:300].strip()
        if len(c.content) > 300:
            preview += "…"
        lines.append(f"\n{preview}\n")
    return "\n".join(lines)


def _entity_page(entity: Entity, chunks: list[ParsedChunk]) -> str:
    lines = [f"# Entity: {entity.canonical}\n"]
    if entity.domain:
        lines.append(f"**Domain:** {entity.domain}")
    if entity.confidence is not None:
        lines.append(f"**Confidence:** {entity.confidence}")
    lines.append("")
    if chunks:
        lines.append("## References\n")
        for c in chunks:
            lines.append(f"- `{c.source_path}` chunk {c.chunk_index}")
    return "\n".join(lines)


def _index_page(domains: list[str], entities: list[Entity]) -> str:
    lines = ["# Tawn Wiki\n"]
    if domains:
        lines.append("## Domains\n")
        for d in sorted(domains):
            lines.append(f"- [domains/{d}](domains/{d}.md)")
    lines.append("")
    if entities:
        lines.append("## Entities\n")
        for e in sorted(entities, key=lambda x: x.canonical):
            lines.append(f"- [entities/{e.canonical}](entities/{e.canonical}.md)")
    return "\n".join(lines)


def generate_wiki(
    chunks: list[ParsedChunk],
    entities: list[Entity],
    wiki_dir: Path,
) -> None:
    """Write wiki pages to .staging/, then atomically swap into wiki_dir."""
    staging = wiki_dir / ".staging"
    if staging.exists():
        shutil.rmtree(staging)
    (staging / "domains").mkdir(parents=True)
    (staging / "entities").mkdir(parents=True)

    # Group chunks by domain
    by_domain: dict[str, list[ParsedChunk]] = defaultdict(list)
    for chunk in chunks:
        domain = chunk.frontmatter.get("domain") or "unknown"
        by_domain[domain].append(chunk)

    # Domain pages
    for domain, domain_chunks in by_domain.items():
        (staging / "domains" / f"{domain}.md").write_text(
            _domain_page(domain, domain_chunks)
        )

    # Entity pages — chunks that mention the entity name
    for entity in entities:
        name_lower = entity.canonical.lower()
        related = [
            c for c in chunks if name_lower in c.content.lower()
        ]
        (staging / "entities" / f"{entity.canonical}.md").write_text(
            _entity_page(entity, related)
        )

    # Index
    (staging / "index.md").write_text(
        _index_page(list(by_domain.keys()), entities)
    )

    # Atomic swap: move staged files into wiki_dir
    # Preserve conflicts.md from live wiki if it exists
    conflicts_src = wiki_dir / "conflicts.md"
    conflicts_txt = conflicts_src.read_text() if conflicts_src.exists() else None

    # Replace live wiki contents with staging
    for item in wiki_dir.iterdir():
        if item.name == ".staging":
            continue
        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()

    for item in staging.iterdir():
        shutil.move(str(item), wiki_dir / item.name)

    # Restore conflicts.md
    if conflicts_txt is not None:
        (wiki_dir / "conflicts.md").write_text(conflicts_txt)

    shutil.rmtree(staging)


# ── Domain-indexed API (plan spec) ────────────────────────────────────────────

def _template_index(domain: str, entities: list[str], recent_chunks: list[str]) -> str:
    entity_list = "\n".join(f"- {e}" for e in entities[:20]) or "_(none yet)_"
    recent_list = "\n".join(
        f"- {c[:120].replace(chr(10), ' ')}..." if len(c) > 120 else f"- {c}"
        for c in recent_chunks[:10]
    ) or "_(none yet)_"
    return (
        f"# {domain.title()} — Knowledge Index\n\n"
        f"## Key Entities\n\n{entity_list}\n\n"
        f"## Recent Notes\n\n{recent_list}\n\n"
        f"---\n_Auto-generated by Tawn Compiler. Edit `raw/` sources to update._\n"
    )


def generate_domain_index(
    domain: str,
    entities: list[str],
    recent_chunks: list[str],
    wiki_dir: Path,
    staging_dir: Path,
    router=None,
) -> None:
    """Write domain index.md to staging_dir/<domain>/index.md.

    Uses router for LLM summary when available; falls back to template.
    """
    domain_staging = staging_dir / domain
    domain_staging.mkdir(parents=True, exist_ok=True)
    index_path = domain_staging / "index.md"

    if router is not None and recent_chunks:
        try:
            from tawn.model.types import Message
            prompt = (
                f"Write a concise wiki index for the '{domain}' domain. "
                f"Key entities: {', '.join(entities[:10])}. "
                f"Recent notes: {' | '.join(recent_chunks[:5])}. "
                f"Output markdown with a brief summary and entity list."
            )
            msgs = [Message(role="user", content=prompt)]
            text = ""
            for chunk in router.stream(msgs):
                text += chunk.text
                if chunk.done:
                    break
            if text.strip():
                index_path.write_text(text)
                return
        except Exception:
            pass

    index_path.write_text(_template_index(domain, entities, recent_chunks))


def atomic_swap(staging_dir: Path, wiki_dir: Path) -> None:
    """Move all domain dirs from staging_dir into wiki_dir atomically.

    Each domain moves individually; failures leave prior wiki content intact.
    """
    if not staging_dir.exists():
        return
    for domain_staging in staging_dir.iterdir():
        if not domain_staging.is_dir() or domain_staging.name.startswith("."):
            continue
        dest = wiki_dir / domain_staging.name
        tmp = wiki_dir / f".{domain_staging.name}.tmp"
        if dest.exists():
            shutil.move(str(dest), str(tmp))
        shutil.move(str(domain_staging), str(dest))
        if tmp.exists():
            shutil.rmtree(tmp)
