"""stage9 observer — observer_sessions and observed_events

Revision ID: a1c4f9b02e77
Revises: d0a417745dbd
Create Date: 2026-07-26

Written by hand rather than autogenerated: alembic.ini pins an in-memory
SQLite URL, and autogenerate in this repo injects a `pgvector...VECTOR(dim=…)`
reference with no import on every revision. Two tables with no vector columns
are cheaper to state directly than to generate and then repair.
"""

from alembic import op
import sqlalchemy as sa

revision = "a1c4f9b02e77"
down_revision = "d0a417745dbd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())

    if "observer_sessions" not in existing:
        op.create_table(
            "observer_sessions",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("project", sa.String(length=128), nullable=False),
            sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("closed_by", sa.String(length=16), nullable=True),
            sa.Column(
                "event_count", sa.Integer(), server_default="0", nullable=False
            ),
            sa.Column("note_path", sa.Text(), nullable=True),
            sa.Column(
                "note_state",
                sa.String(length=16),
                server_default="open",
                nullable=False,
            ),
            sa.Column(
                "note_attempts", sa.Integer(), server_default="0", nullable=False
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            "ix_observer_sessions_project", "observer_sessions", ["project"]
        )

    if "observed_events" not in existing:
        op.create_table(
            "observed_events",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("session_id", sa.Integer(), nullable=True),
            sa.Column("project", sa.String(length=128), nullable=False),
            sa.Column("path", sa.Text(), nullable=False),
            sa.Column("kind", sa.String(length=16), nullable=False),
            sa.Column(
                "lines_added", sa.Integer(), server_default="0", nullable=False
            ),
            sa.Column(
                "lines_removed", sa.Integer(), server_default="0", nullable=False
            ),
            sa.Column(
                "actor",
                sa.String(length=64),
                server_default="unknown",
                nullable=False,
            ),
            sa.Column(
                "confidence", sa.String(length=8), server_default="low", nullable=False
            ),
            sa.Column(
                "basis", sa.String(length=16), server_default="none", nullable=False
            ),
            sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["session_id"], ["observer_sessions.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index("ix_observed_events_project", "observed_events", ["project"])
        op.create_index(
            "ix_observed_events_session_id", "observed_events", ["session_id"]
        )


def downgrade() -> None:
    op.drop_table("observed_events")
    op.drop_table("observer_sessions")
