"""stage8: ledger rollups

Note on `chunks.embedding`: autogenerate wants to alter its type on every
revision, because the column is Vector on Postgres and Text on SQLite and the
model resolves that at import time from local config. It is decided per
installation at table-creation time and must never be migrated — changing the
embedding model is a re-embed, not a schema change. That diff is deliberately
omitted.

Revision ID: d0a417745dbd
Revises: 0003dimensionless
Create Date: 2026-07-26 20:16:21.897163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0a417745dbd'
down_revision: Union[str, None] = '0003dimensionless'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_watermark',
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('byte_offset', sa.Integer(), nullable=False),
    sa.Column('entries_seen', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('path')
    )
    op.create_table('model_call_rollups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('caller', sa.String(length=16), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unpriced_calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_call_rollups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_call_rollups_day'), ['day'], unique=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('model_call_rollups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_call_rollups_day'))

    op.drop_table('model_call_rollups')
    op.drop_table('ledger_watermark')
    # ### end Alembic commands ###
